### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by chenchaohan** [MrWangJustToDo/ts-next-blog#1]
```node
E:\ts-next-blog\node_modules\ts-node\src\index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
server/middleware/apiHandler.ts:51:11 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | Error'.
  Type 'unknown' is not assignable to type 'Error'.

51       log(e, "error");
             ~
server/middleware/apiHandler.ts:56:48 - error TS2322: Type 'unknown' is not assignable to type 'Error'.

56           await errorHandler({ req, res, next, e, code: 404, cache });
                                                  ~

  types/server.ts:40:3
    40   e: Error;
         ~
    The expected type comes from property 'e' which is declared here on type 'ErrorHandlerProps'
server/middleware/apiHandler.ts:59:53 - error TS2571: Object is of type 'unknown'.

59         fail({ res, resDate: { state: "访问失败", data: e.toString() } });
                                                       ~
server/middleware/apiHandler.ts:70:9 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | Error'.
  Type 'unknown' is not assignable to type 'Error'.

70     log(e, "error");
           ~
server/middleware/apiHandler.ts:75:46 - error TS2322: Type 'unknown' is not assignable to type 'Error'.

75         await errorHandler({ req, res, next, e, code: 404, cache });
                                                ~

  types/server.ts:40:3
    40   e: Error;
         ~
    The expected type comes from property 'e' which is declared here on type 'ErrorHandlerProps'
server/middleware/apiHandler.ts:78:51 - error TS2571: Object is of type 'unknown'.

78       fail({ res, resDate: { state: "访问失败", data: e.toString() } });
                                                     ~

    at createTSError (E:\ts-next-blog\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (E:\ts-next-blog\node_modules\ts-node\src\index.ts:517:19)
    at getOutput (E:\ts-next-blog\node_modules\ts-node\src\index.ts:752:36)
    at Object.compile (E:\ts-next-blog\node_modules\ts-node\src\index.ts:968:32)
    at Module.m._compile (E:\ts-next-blog\node_modules\ts-node\src\index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (E:\ts-next-blog\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
```

**Comment by MrWangJustToDo** [comment]
…  麻烦贴出运行平台环境和相应的版本😂

**Comment by MrWangJustToDo** [comment]
我本地只有mac和linux环境

**Comment by MrWangJustToDo** [comment]
resolve  [recent commit](https://github.com/MrWangJustToDo/ts-next-blog/commit/25d7b64dd0cdefb0b3a1d23118ff0e776466562b)
